config/routes.rb
Big2stats::Application.routes.draw do  

resources :users do  
  collection do  
    post :edit_individual  
    put :update_individual
  end
end
resources :users
root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :first_place, :second_place, :third_place, :fourth_place
  validates_presence_of :name, :first_place, :second_place, :third_place, :fourth_place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_url, :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice  => "Successfully updated user."
    else
      render :action => 'edit'
    end
	
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, :notice => "Successfully destroyed user."
  end
  	def edit_individual  
	  @users = User.find(params[:user_ids])  
	  if !@users 
		flash[:notice] = "No users selected"  
		redirect_to users_url
	  end
	end  
	  
	def update_individual  
	  User.update(params[:users].keys, params[:users].values)  
	  flash[:notice] = "Users updated"  
	  redirect_to users_url  
	end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
	<%= stylesheet_link_tag "jquery-ui-1.8.13.custom.css" %>
    <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag "jquery.tablesorter.min.js" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_fields.html.erb
<tr>
  <td><%= f.text_field :name, :size => '15', :disabled => 'true' %></td>
  <td><%= f.text_field :first_place, :size => '5' %></td>
  <td><%= f.text_field :second_place, :size => '5' %></td>
  <td><%= f.text_field :third_place, :size => '5' %></td>
  <td><%= f.text_field :fourth_place, :size => '5' %></td>
</tr>

app/views/users/_form.html.erb
<% form_for @user do |f| %>  
 <% if @user.errors.any? %>  
  <div id="flash_error">  
    <h3><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>  
    <ul>  
    <% @user.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>  
  <% end %>  
  
	  <%= f.text_field :name, :size => '15', :placeholder=>"Name" %><br />
	  <%= f.text_field :first_place, :size => '15', :placeholder=>"First Place" %><br />
	  <%= f.text_field :second_place, :size => '15', :placeholder=>"Second Place" %><br />
	  <%= f.text_field :third_place, :size => '15', :placeholder=>"Third Place" %><br />
	  <%= f.text_field :fourth_place, :size => '15', :placeholder=>"Fourth Place" %><br />

	<p><%= f.submit "Submit" %></p>  
<% end %>  

app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @user %> |
  <%= link_to "View All", users_path %> | 
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %>
</p>

app/views/users/edit_individual.html.erb
<% content_for :title do %>  
  Update Scores
<% end %>  

  
<%= form_tag update_individual_users_path, :method => :put do %>
<table id="scoreboard">
<thead>
  <tr>
    <th><a href="">Name</a></th>
    <th><a href="" class="medal gold"> </a></th>
    <th><a href="" class="medal silver"> </a></th>
    <th><a href="" class="medal bronze"> </a></th>
    <th><a href="" class="medal crap"> </a></th>
  </tr>
  </thead>
  <tbody>
  <% for user in @users %>  
    <%= fields_for "users[]", user do |f| %>  
      <%= render "fields", :f => f %>  
    <% end %>  
  <% end %>  
  </tbody>
	
</table>
  <p><%= submit_tag "Submit" %> </p>  
  <%= link_to "View All", users_path %>
<% end %> 

app/views/users/index.html.erb
<% title "Users" %>
<% form_tag (edit_individual_users_path), :id => 'edit_users' do  %>  
<table id="scoreboard" class="tablesorter">
  <thead>
  <tr>
    <th><a href="#">Name</a></th>
    <th><a href="#" class="medal gold"> </a></th>
    <th><a href="#" class="medal silver"> </a></th>
    <th><a href="#" class="medal bronze"> </a></th>
    <th><a href="#" class="medal crap"> </a></th>
	<th><a href="#">Games</a></th>
	<th><a href="#">Points</a></th>
	<th><a href="#">PPG</a></th>
	<td class="">UPDATE</td>
  </tr>
  </thead>
  <tbody>
	<% total_games = 0 %>
	<% total_first = 0 %>
	<% total_second = 0 %>
	<% total_third = 0 %>
	<% total_fourth = 0 %>
  <% for user in @users %> 
    <tr>
      <td class="user_name"><%= link_to user.name, edit_user_path(user) %></td>
      <td><%= user.first_place %></td>
      <td><%= user.second_place %></td>
      <td><%= user.third_place %></td>
      <td><%= user.fourth_place %></td>
	  <td><%= games=user.first_place+user.second_place+user.third_place+user.fourth_place %>
	  <td><%= points=user.first_place*9+user.second_place*6+user.third_place*3+user.fourth_place*0 %>
		  <% if games!=0 %>
		  <% ppg = points.to_f/games.to_f %>
			<td><%= ppg.round(2)%></td>
		  <% else %>
			<td>0</td>
		  <% end %>
	<% link_to "Show", user %>
    <% link_to "Edit", edit_user_path(user) %>
    <% link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %>
	<td><span class="checkbox"><%= check_box_tag 'user_ids[]', user.id, false, {:id => 'user_id_'+user.id.to_s} %></span></td>
    </tr>
	<% total_first = total_first + user.first_place %>
	<% total_second = total_second + user.second_place %>
	<% total_third = total_third + user.third_place %>
	<% total_fourth = total_fourth + user.fourth_place %>
	<% total_games = total_games + games %>  
  <% end %>
  </tbody>
	<% if (total_first == total_second) && (total_first == total_third) && (total_first == total_fourth) %>
		<tr class="totals green">
	<% else %>
		<tr class="totals red">
	<% end %>
		<td>Totals: </td>
		<td><%= total_first %></td>
		<td><%= total_second %></td>
		<td><%= total_third %></td>
		<td><%= total_fourth %></td>
		<td colspan="3"></td>
		<td><%= submit_tag "Edit" %></td>
	</tr>
	
</table>
<% end %>
<p><%= link_to "New User", new_user_path %></p>

app/views/users/new.html.erb
<% title "New User" %>

<%= render 'form' %>

<p><%= link_to "Back to List", users_path %></p>

app/views/users/show.html.erb
<% title "User" %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>First Place:</strong>
  <%= @user.first_place %>
</p>
<p>
  <strong>Second Place:</strong>
  <%= @user.second_place %>
</p>
<p>
  <strong>Third Place:</strong>
  <%= @user.third_place %>
</p>
<p>
  <strong>Fourth Place:</strong>
  <%= @user.fourth_place %>
</p>

<p>
  <%= link_to "Edit", edit_user_path(@user) %> |
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>